import "./globals.css"

export const metadata = {
	title: "Car Auctions",
	description: "Generated by create next app"
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				Nav Bar will go here
				<main className="container mx-auto px-5 pt-10">{children}</main>
			</body>
		</html>
	)
}
